[build]
  command = "npm ci && npm run build:debug"
  # For Next.js with Netlify plugin, let the plugin handle the publish directory
  # publish = "."  # Comment out to let @netlify/plugin-nextjs handle this

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  # Set Netlify flag for conditional logic
  NETLIFY = "true"
  # Add npm config for better compatibility
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  # Note: @netlify/plugin-nextjs v5.12.0 does not accept any input parameters
  # The plugin automatically detects and configures Next.js settings

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { "!Path" = ["/api/*", "/_next/*", "/favicon.ico", "/robots.txt", "/sitemap.xml"] }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
