[build]
  command = "npm ci && npm run build"
  # Change from 'out' to '.next' for dynamic Next.js apps with API routes
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  # Remove export-related environment variables for dynamic rendering
  # NEXT_PRIVATE_TARGET = "export"  # Removed
  # NEXT_EXPORT = "true"  # Removed

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    # Enable dynamic features for Next.js 15
    nextRuntime = "nodejs18.x"
    # Keep image optimization enabled for dynamic apps
    disable_image_optimization = false
    # Enable server-side rendering and API routes
    target = "server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { "!Path" = ["/api/*", "/_next/*", "/favicon.ico", "/robots.txt", "/sitemap.xml"] }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
