[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_TARGET = "export"
  NEXT_EXPORT = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    nextRuntime = "experimental-edge"
    disable_image_optimization = true
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { "!Path" = ["/api/*", "/_next/*", "/favicon.ico", "/robots.txt", "/sitemap.xml"] }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
